services:
  pcgf.autodrafts.listener:
    class: pcgf\autodrafts\event\listener
    arguments:
      - '@user'
      - '@template'
      - '@config'
      - '@dbal.conn'
    tags:
      - { name: event.listener }